### ISSUE TITLE
 controlador ssd1306(i2c)

### ISSUE THREAD

**Issue by danydeitu** [ISPC-TST-Electronica-Microcontrolada/Grupo2#56]

**Comment by Gona79** [comment]
@danydeitu Estimado, preste atencion a que no subio nada en los commits que hizo. Esto sucede por ejemplo, cuando quiere subir los archivos y los tiene abiertos y sin guardar...

![image](https://user-images.githubusercontent.com/84986194/188256116-321ddc40-74b3-4a47-99a4-d02969a685e5.png)
